name: .NET Build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: dotnet restore github4women/github4women.csproj

    - name: Build
      run: dotnet build github4women/github4women.csproj --no-restore

    - name: Test
      run: dotnet test github4women/github4women.csproj --no-build

    - name: Custom Script Example
      run: echo "This is a custom script step."